'use client'

import { useState } from 'react'
import { Target, X } from 'lucide-react'

const DAYS = [{ value: 1, label: 'L' }, { value: 2, label: 'M' }, { value: 3, label: 'M' }, { value: 4, label: 'J' }, { value: 5, label: 'V' }, { value: 6, label: 'S' }, { value: 0, label: 'D' }]
export default function NutritionGoalDrawer({ query }: { query: string }) {
  const [open, setOpen] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [form, setForm] = useState({ startDate: new Date().toISOString().slice(0, 10), calories: '2100', proteinPercent: 30, fatPercent: 30, carbsPercent: 40, saturatedFat: '', cholesterol: '', fibers: '', sugars: '', sodium: '', days: '1,2,3,4,5,6,0', repeatWeeks: 4 })
  function toggleDay(day: number) { const current = form.days.split(',').map(Number); const next = current.includes(day) ? current.filter(value => value !== day) : [...current, day]; setForm({ ...form, days: (next.length ? next : [day]).join(',') }) }
  function updateMacro(field: 'proteinPercent' | 'fatPercent', value: number) { const other = field === 'proteinPercent' ? form.fatPercent : form.proteinPercent; const carbs = Math.max(0, 100 - value - other); setForm({ ...form, [field]: value, carbsPercent: carbs }) }
  async function save() { setBusy(true); setError(''); const numberOrNull = (value: string) => value ? Number(value) : null; const payload = { ...form, calories: Number(form.calories), saturatedFat: numberOrNull(form.saturatedFat), cholesterol: numberOrNull(form.cholesterol), fibers: numberOrNull(form.fibers), sugars: numberOrNull(form.sugars), sodium: numberOrNull(form.sodium) }; const res = await fetch(`/api/nutrition-goals?${query}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const body = await res.json(); setBusy(false); if (!res.ok) { setError(body.error || 'Salvarea a eșuat.'); return } setOpen(false) }
  return <><button onClick={() => setOpen(true)} className="btn-secondary flex items-center gap-1.5 text-sm"><Target size={15}/>Obiectiv nutriție</button>{open && <><button className="drawer-backdrop" onClick={() => setOpen(false)} aria-label="Închide"/><aside className="plan-drawer"><div className="flex items-center justify-between border-b border-gray-100 pb-4 mb-5"><div><p className="page-kicker">NUTRIȚIE</p><h2 className="text-xl font-semibold mt-1">Adaugă obiectiv nutrițional</h2></div><button onClick={() => setOpen(false)} className="w-9 h-9 rounded-full border border-gray-200 grid place-items-center"><X size={16}/></button></div>{error && <p className="text-sm text-red-600 mb-3">{error}</p>}<div className="space-y-5"><label className="block text-sm">Data de început<input type="date" className="field mt-1" value={form.startDate} onChange={e => setForm({ ...form, startDate: e.target.value })}/></label><label className="block text-sm">Calorii zilnice<input type="number" className="field mt-1" value={form.calories} onChange={e => setForm({ ...form, calories: e.target.value })} placeholder="Kilocalorii (kcal)"/></label>
    <div className="grid grid-cols-3 gap-3"><Macro label="Proteine" value={form.proteinPercent} color="#41bd80" onChange={value => updateMacro('proteinPercent', value)}/><Macro label="Grăsimi" value={form.fatPercent} color="#ef9c45" onChange={value => updateMacro('fatPercent', value)}/><div><p className="text-sm">Carbohidrați</p><p className="text-xs text-gray-400 mt-1">{form.carbsPercent}%</p><div className="h-1.5 rounded bg-[#9b78df] mt-5"/></div></div>
    <div className="grid grid-cols-2 gap-3">{([['saturatedFat','Grăsimi saturate'],['cholesterol','Colesterol'],['fibers','Fibre'],['sugars','Zaharuri'],['sodium','Sodiu']] as const).map(([key, label]) => <label key={key} className="text-sm">{label}<input type="number" className="field mt-1" value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })}/></label>)}</div>
    <div><p className="text-sm mb-2">Repetă în zilele</p><div className="grid grid-cols-7 gap-2">{DAYS.map(day => <button key={day.value} onClick={() => toggleDay(day.value)} className={`day-toggle ${form.days.split(',').includes(String(day.value)) ? 'day-toggle-active' : ''}`}>{day.label}</button>)}</div></div><label className="block text-sm">Repetă pentru<div className="flex mt-1"><input type="number" min="1" max="52" className="field rounded-r-none" value={form.repeatWeeks} onChange={e => setForm({ ...form, repeatWeeks: Number(e.target.value) })}/><span className="border border-l-0 border-gray-200 rounded-r px-4 flex items-center text-sm">săptămâni</span></div></label></div><div className="drawer-actions"><button onClick={() => setOpen(false)} className="btn-secondary">Renunță</button><button onClick={save} disabled={busy} className="btn-primary">{busy ? 'Se salvează…' : 'Salvează obiectivul'}</button></div></aside></>}</>
}
function Macro({ label, value, color, onChange }: { label: string; value: number; color: string; onChange: (value: number) => void }) { return <label><p className="text-sm">{label}</p><p className="text-xs text-gray-400 mt-1">{value}%</p><input type="range" min="0" max="100" value={value} onChange={e => onChange(Number(e.target.value))} className="w-full mt-3" style={{ accentColor: color }}/></label> }
